# Generated by Django 5.2 on 2025-04-24 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.IntegerField(verbose_name=10)),
                ("vehicle_year", models.IntegerField(verbose_name=4)),
                ("vehicle_plate", models.CharField(max_length=10)),
                ("driving_license", models.CharField(max_length=15)),
                ("rating", models.IntegerField(verbose_name=5)),
            ],
        ),
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.IntegerField(verbose_name=10)),
            ],
        ),
        migrations.CreateModel(
            name="RideDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("destination", models.CharField(max_length=50)),
                ("pickup_time", models.DateField(auto_now_add=True)),
                ("esimated_duration", models.IntegerField(verbose_name=3)),
                ("distance", models.IntegerField(verbose_name=2)),
                ("price", models.IntegerField(verbose_name=4)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("cash", "rider paid driver by cash"),
                            ("card", "rider paid driver by card"),
                        ]
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.driver"
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.rider"
                    ),
                ),
            ],
        ),
    ]
