# Generated by Django 5.2.1 on 2025-05-14 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('vehicle_year', models.CharField(max_length=4)),
                ('vehicle_plate', models.CharField(max_length=10)),
                ('driving_license', models.CharField(max_length=15)),
                ('rating', models.CharField(default=0, max_length=1)),
                ('earnings', models.CharField(default=0)),
                ('available', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RideDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('pickup_time', models.DateTimeField(auto_now_add=True)),
                ('esimated_duration', models.CharField(max_length=3)),
                ('distance', models.CharField(max_length=3)),
                ('price', models.CharField(max_length=4)),
                ('payment_mode', models.CharField(choices=[('cash', 'rider paid driver by cash'), ('card', 'rider paid driver by card')])),
                ('ride_rating', models.CharField(default=2, verbose_name=1)),
                ('review_cleanliness', models.BooleanField(default=0)),
                ('review_friendly', models.BooleanField(default=0)),
                ('review_discipline', models.BooleanField(default=0)),
                ('review_safety', models.BooleanField(default=0)),
                ('review_arrive_on_time', models.BooleanField(default=0)),
                ('status', models.BooleanField(default=1, help_text='1:ongoing , 0:ride ended')),
                ('favourite', models.BooleanField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rider')),
            ],
        ),
    ]
