# Generated by Django 5.2 on 2025-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="driver",
            name="rating",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_year",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="ridedetails",
            name="distance",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="ridedetails",
            name="esimated_duration",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="ridedetails",
            name="price",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="rider",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
