# Generated by Django 5.2.1 on 2025-05-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_driver_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
