# Generated by Django 5.2 on 2025-04-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_driver_phone_number_alter_driver_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ridedetails",
            name="pickup_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
