# Generated by Django 5.2 on 2025-04-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_ridedetails_pickup_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="earnings",
            field=models.IntegerField(default=0),
        ),
    ]
