# Generated by Django 5.2 on 2025-04-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_driver_earnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridedetails",
            name="favourite",
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="ridedetails",
            name="review_arrive_on_time",
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="ridedetails",
            name="review_cleanliness",
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="ridedetails",
            name="review_discipline",
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="ridedetails",
            name="review_friendly",
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="ridedetails",
            name="review_safety",
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name="ridedetails",
            name="ride_rating",
            field=models.PositiveIntegerField(default=2, max_length=1),
        ),
        migrations.AddField(
            model_name="ridedetails",
            name="status",
            field=models.BooleanField(default=1, help_text="1:ongoing , 0:ride ended"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="earnings",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="driver",
            name="phone_number",
            field=models.PositiveIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="driver",
            name="rating",
            field=models.PositiveIntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_year",
            field=models.PositiveIntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name="ridedetails",
            name="distance",
            field=models.PositiveIntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name="ridedetails",
            name="esimated_duration",
            field=models.PositiveIntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name="ridedetails",
            name="price",
            field=models.PositiveIntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name="rider",
            name="phone_number",
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
