# Generated by Django 5.2 on 2025-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_ridedetails_favourite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="phone_number",
            field=models.PositiveIntegerField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name="driver",
            name="rating",
            field=models.PositiveIntegerField(default=0, verbose_name=1),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_year",
            field=models.PositiveIntegerField(verbose_name=4),
        ),
        migrations.AlterField(
            model_name="ridedetails",
            name="distance",
            field=models.PositiveIntegerField(verbose_name=3),
        ),
        migrations.AlterField(
            model_name="ridedetails",
            name="esimated_duration",
            field=models.PositiveIntegerField(verbose_name=3),
        ),
        migrations.AlterField(
            model_name="ridedetails",
            name="price",
            field=models.PositiveIntegerField(verbose_name=4),
        ),
        migrations.AlterField(
            model_name="ridedetails",
            name="ride_rating",
            field=models.PositiveIntegerField(default=2, verbose_name=1),
        ),
        migrations.AlterField(
            model_name="rider",
            name="phone_number",
            field=models.PositiveIntegerField(verbose_name=10),
        ),
    ]
