# Generated by Django 5.2.1 on 2025-05-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_driver_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='available',
            field=models.CharField(default='1'),
        ),
    ]
