# Generated by Django 5.2 on 2025-06-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_esimated_duration_ridedetails_estimated_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='available',
        ),
        migrations.AddField(
            model_name='driver',
            name='total_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_rides',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='earnings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ridedetails',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ridedetails',
            name='ride_rating',
            field=models.FloatField(default=0),
        ),
    ]
