# Generated by Django 5.2.1 on 2025-06-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_driver_total_rating_driver_total_rides_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='available',
        ),
        migrations.AlterField(
            model_name='ridedetails',
            name='ride_rating',
            field=models.FloatField(default=0),
        ),
    ]
