import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121212',
    paddingTop: 20,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 15,
  },
  header: {
    fontSize: 24,
    fontFamily: 'Poppins-Bold',
    color: '#4CAF50',
    letterSpacing: 0.5,
  },
  refreshButton: {
    padding: 8,
  },
  rideCard: {
    backgroundColor: '#1E1E1E',
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 20,
    marginBottom: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#4CAF50',
    shadowColor: '#4CAF50',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  rideHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
    paddingBottom: 8,
  },
  rideTitle: {
    fontSize: 18,
    fontFamily: 'Poppins-SemiBold',
    color: '#4CAF50',
  },
  rideDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  rideDetailText: {
    color: '#E0E0E0',
    fontFamily: 'Poppins-Regular',
    marginLeft: 8,
    fontSize: 14,
  },
  statsContainer: {
    flexDirection: 'row',
    marginTop: 12,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  statPill: {
    backgroundColor: '#2A2A2A',
    borderRadius: 16,
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginRight: 8,
    marginBottom: 8,
  },
  pricePill: {
    backgroundColor: '#1B3B1A',
  },
  statText: {
    color: '#E0E0E0',
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
  },
  priceText: {
    color: '#4CAF50',
    fontFamily: 'Poppins-SemiBold',
  },
  driverContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#333',
  },
  driverText: {
    color: '#E0E0E0',
    fontFamily: 'Poppins-Regular',
    marginLeft: 8,
    fontSize: 14,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 'auto',
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  ratingText: {
    color: '#4CAF50',
    fontFamily: 'Poppins-SemiBold',
    marginLeft: 4,
    fontSize: 14,
  },
  listContainer: {
    paddingBottom: 30,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#121212',
  },
  loadingText: {
    color: '#4CAF50',
    fontFamily: 'Poppins-Regular',
    marginTop: 16,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#121212',
    padding: 20,
  },
  errorText: {
    color: '#4CAF50',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 18,
    marginTop: 16,
  },
  errorSubText: {
    color: '#BDBDBD',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 20,
    backgroundColor: '#4CAF50',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#121212',
    fontFamily: 'Poppins-SemiBold',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#121212',
    padding: 20,
  },
  emptyTitle: {
    color: '#4CAF50',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 20,
    marginTop: 16,
  },
  emptySubtitle: {
    color: '#BDBDBD',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
  },
});