import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#0a0a0a',
    },
    header: {
      alignItems: 'center',
      paddingTop: 60,
      paddingBottom: 30,
      paddingHorizontal: 20,
      backgroundColor: '#1a1a1a',
    },
    title: {
      fontSize: 32,
      fontWeight: 'bold',
      color: '#ffffff',
      marginTop: 10,
      marginBottom: 8,
    },
    subtitle: {
      fontSize: 16,
      color: '#888',
      textAlign: 'center',
    },
    formContainer: {
      paddingHorizontal: 20,
      paddingTop: 20,
    },
    label: {
      fontSize: 16,
      fontWeight: '600',
      color: '#ffffff',
      marginBottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
    },
    dropdownButtonStyle: {
      width: '100%',
      height: 56,
      backgroundColor: '#1a1a1a',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#333',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      marginBottom: 20,
    },
    dropdownButtonOpen: {
      borderColor: '#00ff7f',
      borderWidth: 2,
    },
    dropdownButtonTxtStyle: {
      fontSize: 16,
      color: '#ffffff',
      flex: 1,
      textAlign: 'left',
    },
    placeholderText: {
      color: '#666',
    },
    dropdownMenuStyle: {
      backgroundColor: '#1a1a1a',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#333',
      marginTop: 4,
    },
    dropdownItemStyle: {
      paddingHorizontal: 16,
      paddingVertical: 14,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: '#333',
    },
    selectedItem: {
      backgroundColor: '#2a2a2a',
    },
    dropdownItemTxtStyle: {
      fontSize: 16,
      color: '#ffffff',
      flex: 1,
    },
    selectedItemText: {
      color: '#00ff7f',
      fontWeight: '500',
    },
    searchInputStyle: {
      backgroundColor: '#2a2a2a',
      borderBottomWidth: 1,
      borderBottomColor: '#333',
      paddingHorizontal: 16,
      paddingVertical: 12,
      fontSize: 16,
      color: '#ffffff',
    },
    submitButton: {
      backgroundColor: '#00ff7f',
      paddingVertical: 16,
      paddingHorizontal: 24,
      borderRadius: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 20,
    },
    submitButtonDisabled: {
      opacity: 0.6,
    },
    submitButtonText: {
      color: '#000',
      fontSize: 16,
      fontWeight: '600',
      marginLeft: 8,
    },
    resultsContainer: {
      marginTop: 20,
    },
    summaryContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 30,
    },
    summaryCard: {
      backgroundColor: '#1a1a1a',
      borderRadius: 12,
      padding: 16,
      alignItems: 'center',
      flex: 1,
      marginHorizontal: 4,
      borderWidth: 1,
      borderColor: '#333',
    },
    summaryValue: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#ffffff',
      marginTop: 8,
      marginBottom: 4,
    },
    summaryLabel: {
      fontSize: 12,
      color: '#888',
      textAlign: 'center',
    },
    chartContainer: {
      backgroundColor: '#1a1a1a',
      borderRadius: 16,
      padding: 16,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: '#333',
    },
    chartTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: '#ffffff',
      marginBottom: 16,
      flexDirection: 'row',
      alignItems: 'center',
    },
    chart: {
      borderRadius: 16,
    },
    selectedPointInfo: {
      backgroundColor: '#00ff7f',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 8,
      alignSelf: 'center',
      marginTop: 10,
    },
    selectedPointText: {
      color: '#000',
      fontWeight: '600',
      fontSize: 14,
    },
    tableContainer: {
      backgroundColor: '#1a1a1a',
      borderRadius: 16,
      padding: 16,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: '#333',
    },
    tableTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: '#ffffff',
      marginBottom: 16,
      flexDirection: 'row',
      alignItems: 'center',
    },
    tableHeader: {
      flexDirection: 'row',
      paddingVertical: 12,
      borderBottomWidth: 2,
      borderBottomColor: '#00ff7f',
      marginBottom: 8,
    },
    tableHeaderText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '600',
      color: '#00ff7f',
      textAlign: 'center',
    },
    tableScrollView: {
      maxHeight: 300,
    },
    tableRow: {
      flexDirection: 'row',
      paddingVertical: 12,
      paddingHorizontal: 8,
      borderBottomWidth: 1,
      borderBottomColor: '#333',
      alignItems: 'center',
    },
    bestHourRow: {
      backgroundColor: '#2a2a2a',
      borderRadius: 8,
      borderBottomColor: '#00ff7f',
    },
    tableCell: {
      flex: 1,
      fontSize: 14,
      color: '#ffffff',
      textAlign: 'center',
    },
    earningsCell: {
      fontWeight: '600',
      color: '#00ff7f',
    },
    locationCell: {
      fontSize: 12,
    },
    starIcon: {
      marginLeft: 8,
    },
  });
  export default styles